import type { CommandRegistrar } from "@framework/types.js";

import suggestHarnessOrchestrator from "@/orchestrators/suggest-harness-orchestrator.js";

/**
 * Registers the `praxis harness` command group.
 *
 * The slow loop's surface (08): Praxis emits a brief, a coding agent
 * drafts the change (via the generated /praxis-harness command), a
 * human ratifies the PR. Praxis never edits the harness.
 */
const harnessCommand: CommandRegistrar = (program) => {
  const harness = program
    .command("harness")
    .description("Evidence about which harness elements to change — brief, never edit");

  harness
    .command("suggest")
    .description("Assemble the harness brief from the ledger: evidence, suggested diagnoses")
    .option(
      "--since <dateOrRef>",
      "only runs at or after this ISO date, or a git ref's commit date",
    )
    .option("--branch <name>", "only runs recorded on this branch")
    .option("--json", "the brief as the stable machine contract")
    .addHelpText(
      "after",
      `
When to use: on demand or per period, never per run (08) — when you
want to know which axiom keeps firing and whether the suspect is the
harness, the spec, or the reviewer. Pure read; diagnoses are suggested,
the call is yours. /praxis-harness (generated by praxis compile) walks
a coding agent through drafting the change as a reviewable PR.

Example:
  $ praxis harness suggest --since 2026-09-01`,
    )
    .action(suggestHarnessOrchestrator);
};

export default harnessCommand;
